version: '2'
services:
  web:
    mem_limit: 100000000
    image: thinkspill/temperature-api-web
    links:
      - gearman
    ports:
      - 80:80
  worker:
    mem_limit: 100000000
    image: thinkspill/temperature-api-worker
    links:
      - gearman
  gearman:
    mem_limit: 100000000
    image: thinkspill/temperature-api-gearman

# ecs-cli compose --project-name TemperatureAPI -f ecs-compose.yml service up
